/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Doctor;

import java.awt.List;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Doctor.Doctor;
import model.Doctor.DoctorDirectory;
import model.Encounter.Encounter;
import model.Encounter.VitalSigns;
import model.Hospital.HospitalDirectory;
import model.Patient.Patient;
import model.Patient.PatientDirectory;
import model.Person.PersonDirectory;
import ui.Admin.MainJFrame;

/**
 *
 * @author Harshada
 */
public class DoctorHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form DoctorHomeScreen
     */
    PatientDirectory patientList;
    PatientDirectory doctorpatientList;
    Patient patient;
    PersonDirectory personList;
    DoctorDirectory doctorList;
    HospitalDirectory hospitalList;
    Encounter encounter;
    VitalSigns vitalSigns;
    Doctor doctor;
    public DoctorHomeScreen(PersonDirectory personList1, DoctorDirectory doctorList1,PatientDirectory patientList1, PatientDirectory doctorpatientList1, HospitalDirectory hospitalList1, Doctor doctor1) {
        initComponents();
        this.patientList = patientList1;
        this.doctorpatientList = doctorpatientList1;
        this.personList = personList1;
        this.doctorList = doctorList1;
        this.hospitalList = hospitalList1;
        this.doctor = doctor1;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtBodyTemp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPulseRate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRespRate = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnVitalSigns = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(729, 574));
        setPreferredSize(new java.awt.Dimension(729, 574));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("ADD VITAL SIGNS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 172, 47));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("BODY TEMPERATURE ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, 50));
        getContentPane().add(txtBodyTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 180, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PULSE RATE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 104, 30));
        getContentPane().add(txtPulseRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 180, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("RESPIRATION RATE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 150, 30));
        getContentPane().add(txtRespRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 180, 30));
        getContentPane().add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 180, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("BLOOD PRESSURE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, 30));

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient Name", "Disease", "Phone No", "Age"
            }
        ));
        jScrollPane2.setViewportView(tblPatient);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 580, 165));

        btnVitalSigns.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVitalSigns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/plus (1).png"))); // NOI18N
        btnVitalSigns.setText("ADD VITAL SIGNS");
        btnVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalSignsActionPerformed(evt);
            }
        });
        getContentPane().add(btnVitalSigns, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, 40));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 120, 36));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalSignsActionPerformed
        // TODO add your handling code here:
        try
        {
         int selectedRowIndex = tblPatient.getSelectedRow();
        double bloodpressure = Double.parseDouble(txtBloodPressure.getText());
        double pulserate = Double.parseDouble(txtPulseRate.getText());
        double resprate = Double.parseDouble(txtRespRate.getText());
        double bodyTemp = Double.parseDouble(txtBodyTemp.getText());
       
        encounter = new Encounter();
        vitalSigns = new VitalSigns();
        encounter.setDoc(doctor);
        vitalSigns.setBloodPressure(bloodpressure);
        vitalSigns.setPulseRate(pulserate);
        vitalSigns.setRespRate(resprate);
        vitalSigns.setBodyTemp(bodyTemp);
        encounter.setVitalSign(vitalSigns);
        encounter.setAptTime(NewDate());
        DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        System.out.println("In the Update");
        Patient selectedPatient = (Patient) model.getValueAt(selectedRowIndex,0);
        String patientUsername = selectedPatient.person.getUsername();
        if(tblPatient.getSelectedRowCount()==1){
        Patient patientfound = patientList.FindPatient(patientUsername);
        ArrayList<Encounter> tempEncounterList = patientfound.getEncounterHistory();
        tempEncounterList.add(encounter);
        patientfound.setEncounterHistory(tempEncounterList);
        System.out.println("Done Update");
         JOptionPane.showMessageDialog(this, "Vital Signs added");
        populateTable();
        
        }
        }
         catch(Exception e)
        {
             JOptionPane.showMessageDialog(this, "Please try again");
        }
    }//GEN-LAST:event_btnVitalSignsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         MainJFrame frame = new MainJFrame(personList, doctorList,patientList,hospitalList,patient,doctor);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnVitalSigns;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBodyTemp;
    private javax.swing.JTextField txtPulseRate;
    private javax.swing.JTextField txtRespRate;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
        model.setRowCount(0);
        
        for (Patient profile : doctorpatientList.getPatientList()) {
            
            Object[] row = new Object[5];
            row[0] = profile;
            row[1] = profile.getDisease();
            row[2] = profile.person.getPhoneNo();
            row[3] = profile.person.getAge();
            model.addRow(row);
        }
        }
    

    private String NewDate() {
       SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
        Date date = new Date();  
        return formatter.format(date);
    }
}
