/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Admin;

import model.Doctor.Doctor;
import model.Doctor.DoctorDirectory;
import model.Hospital.HospitalDirectory;
import model.Patient.Patient;
import model.Patient.PatientDirectory;
import model.Person.PersonDirectory;

/**
 *
 * @author Harshada
 */
public class AdminOperations extends javax.swing.JFrame {

    /**
     * Creates new form AdminOperations
     */
    PersonDirectory personList;
    DoctorDirectory doctorList;
    PatientDirectory patientList;
    HospitalDirectory hospitalList;
    Patient patient;
    Doctor doctor;
    public AdminOperations() {
        initComponents();
        personList = new PersonDirectory();
        doctorList = new DoctorDirectory();
        patientList = new PatientDirectory();
        hospitalList = new HospitalDirectory();
    }

    public AdminOperations(PersonDirectory personList1, DoctorDirectory doctorList1, PatientDirectory patientList1, HospitalDirectory hospitalList1) {
        initComponents();
        this.personList = personList1;
        this.doctorList = doctorList1;
        this.patientList = patientList1;
        this.hospitalList = hospitalList1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnManageAdmin = new javax.swing.JButton();
        ManagePatients = new javax.swing.JButton();
        ManageDoctors = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(637, 455));
        setPreferredSize(new java.awt.Dimension(637, 455));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCreateUser.setText("REGISTER USER");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 162, 34));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME ADMIN:)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 22, 221, 50));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 161, 37));

        btnManageAdmin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageAdmin.setText("MANAGE ADMINS");
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 162, 34));

        ManagePatients.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManagePatients.setText("MANAGE PATIENTS");
        ManagePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManagePatientsActionPerformed(evt);
            }
        });
        getContentPane().add(ManagePatients, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, 36));

        ManageDoctors.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ManageDoctors.setText("MANAGE DOCTORS");
        ManageDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageDoctorsActionPerformed(evt);
            }
        });
        getContentPane().add(ManageDoctors, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 34));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        RegisterUser user = new RegisterUser(personList,doctorList,patientList,hospitalList);
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainJFrame frame = new MainJFrame(personList, doctorList,patientList,hospitalList,patient,doctor);
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
        // TODO add your handling code here:
        ManageAdmins manageAdmin = new ManageAdmins(personList,doctorList,patientList,hospitalList);
        manageAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnManageAdminActionPerformed

    private void ManagePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManagePatientsActionPerformed
        // TODO add your handling code here:
        ManagePatients managePatients = new ManagePatients(doctorList,personList,patientList,hospitalList);
        managePatients.setVisible(true);
        dispose();
    }//GEN-LAST:event_ManagePatientsActionPerformed

    private void ManageDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageDoctorsActionPerformed
        // TODO add your handling code here:
        ManageDoctorsAdmin mda = new ManageDoctorsAdmin(doctorList,personList,patientList,hospitalList);
        mda.setVisible(true);
        dispose();
    }//GEN-LAST:event_ManageDoctorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageDoctors;
    private javax.swing.JButton ManagePatients;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
