/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Admin;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Doctor.Doctor;
import model.Doctor.DoctorDirectory;
import model.Hospital.HospitalDirectory;
import model.Patient.Patient;
import model.Patient.PatientDirectory;
import model.Person.Person;
import model.Person.PersonDirectory;
import ui.CommunityAdmin.CommunityAdminOperations;
import ui.Doctor.DoctorHomeScreen;
import ui.Patient.PatientOperations;
import ui.Patient.PatientSelfRegistration;

/**
 *
 * @author Harshada
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    PersonDirectory personList;
    PatientDirectory patientList;
    Person person;
    DoctorDirectory doctorList;
    HospitalDirectory hospitalList;
    Doctor doctor;
    Patient patient;

    public MainJFrame() {
        initComponents();
        this.personList = new PersonDirectory();
        this.doctorList = new DoctorDirectory();
        this.patientList = new PatientDirectory();
        this.hospitalList = new HospitalDirectory();
        this.patient = new Patient();
        this.doctor = new Doctor();
    }

    public MainJFrame(PersonDirectory personList1, DoctorDirectory doctorList1, PatientDirectory patientList1, HospitalDirectory hospitalList1, Patient patient, Doctor doctor) {
        initComponents();
        this.personList = personList1;
        this.doctorList = doctorList1;
        this.patientList = patientList1;
        this.hospitalList = hospitalList1;
        this.patient = patient;
        this.doctor = doctor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSelfRegister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(643, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("MEDICAL RESOURCE MANAGEMENT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 6, 397, 53));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 383, 113, 26));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 333, 162, 31));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 382, 162, 31));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 51, 204));
        btnLogin.setText("LOGIN");
        btnLogin.setIconTextGap(0);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 490, 98, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USERNAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 332, 123, 31));

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "COMMUNITY ADMIN", "HOSPITAL ADMIN", "DOCTOR", "PATIENT" }));
        role.setSelectedIndex(-1);
        getContentPane().add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 432, 162, 31));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ROLE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 431, 103, 31));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngwave.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 65, -1, 228));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("If patient , then you can self register");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 230, 30));

        btnSelfRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSelfRegister.setForeground(new java.awt.Color(0, 51, 204));
        btnSelfRegister.setText("SELF REGISTER");
        btnSelfRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelfRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelfRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
try
{

        String username = txtUsername.getText();
        String password = txtPassword.getText();
        String checkRole = (role.getSelectedItem().toString());
        if (username.matches("test") && password.matches("test") && checkRole.equals("ADMIN"))
        {
            JOptionPane.showMessageDialog(this, "User loggedIn Successfully");
            AdminOperations adOperations = new AdminOperations(personList, doctorList, patientList, hospitalList);
            adOperations.setVisible(true);
            dispose();
        }  
        else if (username.matches("test") && password.matches("test") && checkRole.equals("COMMUNITY ADMIN"))
        {
            JOptionPane.showMessageDialog(this, "User loggedIn Successfully");
            CommunityAdminOperations commLogin = new CommunityAdminOperations(personList, doctorList, patientList, hospitalList,doctor,patient);
            commLogin.setVisible(true);
            dispose();
        }  
        else if (personList.loginValues(username, password).equals(checkRole) && checkRole.equals("COMMUNITY ADMIN")) 
        {
            JOptionPane.showMessageDialog(this, "User loggedIn Successfully");
            CommunityAdminOperations commLogin = new CommunityAdminOperations(personList, doctorList, patientList, hospitalList,doctor,patient);
            commLogin.setVisible(true);
            dispose();
        } 
        else if (doctorList.loginValues(username, password).equals(checkRole) && checkRole.equals("DOCTOR")) {
            doctor = doctorList.getLoginValues(username, password);
            if (doctor != null) 
            {
                JOptionPane.showMessageDialog(this, "User loggedIn Successfully");
                DoctorHomeScreen doctorHome = new DoctorHomeScreen(personList, doctorList, patientList, patientList.getDoctorsPatient(username), hospitalList, doctor);
                doctorHome.setVisible(true);
                dispose();
            }
        } 
        else if (patientList.loginValues(username, password).equals(checkRole) && checkRole.equals("PATIENT")) 
        {
            patient = patientList.getLoginValues(username, password);
            if (patient != null) {
                JOptionPane.showMessageDialog(this, "User loggedIn Successfully");
                PatientOperations patientOp = new PatientOperations(personList, doctorList, patientList, hospitalList, patient, doctor);
                patientOp.setVisible(true);
                dispose();
            }
        } 
        else if (personList.loginValues(username, password).equals(checkRole) && checkRole.equals("HOSPITAL ADMIN")) 
        {
           JOptionPane.showMessageDialog(this, "User loggedIn Successfully");
            HospitalAdminLogin hospitalLogin = new HospitalAdminLogin(personList, doctorList, patientList, hospitalList);
            hospitalLogin.setVisible(true);
            dispose();
        } 
        else {
            JOptionPane.showMessageDialog(this, "User loggedIn failed");
        }
  }
       catch(Exception e)
        {
           JOptionPane.showMessageDialog(this, "Please enter username and password and select a role");
       }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSelfRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelfRegisterActionPerformed
        // TODO add your handling code here:
        PatientSelfRegistration ps = new PatientSelfRegistration(personList, doctorList, patientList, hospitalList);
        ps.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSelfRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSelfRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
