/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Patient;

import javax.swing.JOptionPane;
import model.Doctor.Doctor;
import model.Doctor.DoctorDirectory;
import model.Hospital.HospitalDirectory;
import model.Patient.Patient;
import model.Patient.PatientDirectory;
import model.Person.PersonDirectory;
import ui.Admin.MainJFrame;

/**
 *
 * @author Harshada
 */
public class PatientOperations extends javax.swing.JFrame {

    /**
     * Creates new form PatientOperations
     */
    DoctorDirectory doctorList;
    PatientDirectory patientList;
    PersonDirectory personList;
    HospitalDirectory hospitalList;
    Patient patient;
    Doctor doctor;
    public PatientOperations(PersonDirectory personList1, DoctorDirectory doctorList1, PatientDirectory patientList1, HospitalDirectory hospitalList1, Patient patient1, Doctor doctor1) {
        initComponents();
        this.personList = personList1;
        this.doctorList = doctorList1;
        this.patientList = patientList1;
        this.hospitalList = hospitalList1;
        this.patient = patient1;
        this.doctor = doctor1;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSearchDoctor = new javax.swing.JButton();
        btnSearchHospital = new javax.swing.JButton();
        btnViewEncounters = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnbookAppointment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(664, 483));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("PATIENT OPERATIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 19, 200, -1));

        btnSearchDoctor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchDoctor.setText("SEARCH DOCTOR");
        btnSearchDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 82, 192, 41));

        btnSearchHospital.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchHospital.setText("SEARCH HOSPITAL");
        btnSearchHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearchHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 152, 192, 41));

        btnViewEncounters.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewEncounters.setText("VIEW ENCOUNTERS");
        btnViewEncounters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEncountersActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEncounters, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 211, 192, 41));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 357, 80, 40));

        btnbookAppointment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbookAppointment.setText("BOOK APPOINTMENT");
        btnbookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbookAppointmentActionPerformed(evt);
            }
        });
        getContentPane().add(btnbookAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 285, 192, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDoctorActionPerformed
        // TODO add your handling code here:
        try
        {
        SearchDoctor sd = new SearchDoctor(personList, doctorList, patientList, hospitalList);
        sd.setVisible(true);
        dispose();
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(this, "No encounters");
        }
    }//GEN-LAST:event_btnSearchDoctorActionPerformed

    private void btnSearchHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHospitalActionPerformed
        // TODO add your handling code here:
        try
        {
        SearchHospital sh = new SearchHospital(personList, doctorList, patientList, hospitalList);
        sh.setVisible(true);
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(this, "No encounters");
        }
    }//GEN-LAST:event_btnSearchHospitalActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
          try
        {
        MainJFrame frame = new MainJFrame(personList, doctorList, patientList, hospitalList, patient,doctor);
        frame.setVisible(true);
        dispose();
        }    catch(Exception e)
        {
             JOptionPane.showMessageDialog(this, "No encounters");
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnbookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbookAppointmentActionPerformed
        // TODO add your handling code here:
        try
        {
        BookAppointment bookAppointment = new BookAppointment(personList, doctorList, patientList, hospitalList, patient,doctor);
        bookAppointment.setVisible(true);
        dispose();
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(this, "No encounters");
        }
        
    }//GEN-LAST:event_btnbookAppointmentActionPerformed

    private void btnViewEncountersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEncountersActionPerformed
        // TODO add your handling code here:
        try
        {
        ViewEncounters vw = new ViewEncounters(personList, doctorList, patientList, hospitalList, patient,doctor);
        vw.setVisible(true);
        dispose();
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(this, "No encounters");
        }
    }//GEN-LAST:event_btnViewEncountersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchDoctor;
    private javax.swing.JButton btnSearchHospital;
    private javax.swing.JButton btnViewEncounters;
    private javax.swing.JButton btnbookAppointment;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
