/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.Patient;

import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Doctor.Doctor;
import model.Doctor.DoctorDirectory;
import model.Hospital.Hospital;
import model.Hospital.HospitalDirectory;
import model.Patient.Patient;
import model.Patient.PatientDirectory;
import model.Person.PersonDirectory;

/**
 *
 * @author Harshada
 */
public class SearchHospital extends javax.swing.JFrame {

    /**
     * Creates new form SeachHospital
     */
    DoctorDirectory doctorList;
    PatientDirectory patientList;
    Patient patient;
    PersonDirectory personList;
    HospitalDirectory hospitalList;
    DefaultTableModel model;
    Doctor doctor;
    public SearchHospital(PersonDirectory personList1, DoctorDirectory doctorList1,PatientDirectory patientList1, HospitalDirectory hospitalList1) {
        initComponents();
        this.personList = personList1;
        this.doctorList = doctorList1;
        this.patientList = patientList1;
        this.hospitalList = hospitalList1;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(678, 558));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("SEARCH HOSPITAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 22, -1, 45));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("CITY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 113, -1, 34));

        txtCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCityKeyReleased(evt);
            }
        });
        getContentPane().add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 116, 203, 30));

        tblHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Hospital Name", "PhoneNo", "City"
            }
        ));
        jScrollPane1.setViewportView(tblHospital);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 205, -1, 230));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 475, 86, 41));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PatientOperations patientOp = new PatientOperations( personList,  doctorList, patientList,  hospitalList,patient,doctor);
        patientOp.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCityKeyReleased
        // TODO add your handling code here:
        String searchString = txtCity.getText();
       Search(searchString);
    }//GEN-LAST:event_txtCityKeyReleased

    /**
     * @param args the command line arguments
     */
   

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        model.setRowCount(0);

        for (Hospital profile : hospitalList.getHospitalList()) {

            Object[] row = new Object[3];
            row[0] = profile;
            row[1] = profile.getPhoneNo();
            row[2] = profile.city.getCityName();
          
            model.addRow(row);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHospital;
    private javax.swing.JTextField txtCity;
    // End of variables declaration//GEN-END:variables

    private void Search(String searchString) {
       model = (DefaultTableModel) tblHospital.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tblHospital.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(searchString));
    }
}
